import { PageBackground } from '~/components/ui/page-background';
import { QuizAttemptPage } from '~/features/quizzes/components/quiz-attempt';
import { QUIZ_COPY } from '~/features/quizzes/constants/copy';
import { QUIZ_ATTEMPT_COPY } from '~/features/quizzes/constants/quiz-attempt-copy';
import { dataQuizzes } from '~/features/quizzes/data';
import { getCurrentSession } from '~/root';
import type { Route } from './+types/quiz-attempt';
// Type imports will be generated by React Router

export function meta({ data }: Route.MetaArgs) {
  const quizTitle = data?.attempt?.quiz?.title || 'Quiz';
  return [
    { title: QUIZ_ATTEMPT_COPY.meta.title(quizTitle) },
    {
      name: 'description',
      content: QUIZ_ATTEMPT_COPY.meta.description(quizTitle),
    },
  ];
}

export async function loader(args: Route.LoaderArgs) {
  const currentSession = await getCurrentSession(args);
  if (!currentSession) {
    throw new Response('Unauthorized', { status: 401 });
  }

  const { attemptId } = args.params;
  if (!attemptId) {
    throw new Response('Attempt ID is required', { status: 400 });
  }

  // Get attempt with ownership check
  const attempt = await dataQuizzes.getQuizAttempt(
    attemptId,
    currentSession._id
  );
  if (!attempt) {
    throw new Response('Quiz attempt not found', { status: 404 });
  }

  return { attempt, userId: currentSession._id };
}

export default function QuizAttemptRoute(props: Route.ComponentProps) {
  return <QuizAttemptPage {...props.loaderData} />;
}
