import { PageBackground } from '~/components/ui/page-background';
import { QuizAttemptPage } from '~/features/quizzes/components/quiz-attempt';
import { dataQuizzes } from '~/features/quizzes/data';
import { getCurrentSession } from '~/root';
import type { Route } from './+types/quiz-attempt';
// Type imports will be generated by React Router

export function meta({ data }: Route.MetaArgs) {
  return [
    { title: `${data?.attempt?.quiz?.title || 'Quiz'} Attempt | Genii` },
    {
      name: 'description',
      content: `Taking quiz: ${data?.attempt?.quiz?.title || 'Quiz'}`,
    },
  ];
}

export async function loader(args: Route.LoaderArgs) {
  const currentSession = await getCurrentSession(args);
  if (!currentSession) {
    throw new Response('Unauthorized', { status: 401 });
  }

  const { attemptId } = args.params;
  if (!attemptId) {
    throw new Response('Attempt ID is required', { status: 400 });
  }

  // Get attempt with ownership check
  const attempt = await dataQuizzes.getQuizAttempt(
    attemptId,
    currentSession._id
  );
  if (!attempt) {
    throw new Response('Quiz attempt not found', { status: 404 });
  }

  return { attempt, userId: currentSession._id };
}

export default function QuizAttemptRoute(props: Route.ComponentProps) {
  return (
    <PageBackground variant="amber-indigo">
      <QuizAttemptPage {...props.loaderData} />
    </PageBackground>
  );
}
